[window]
opacity = 0.95
blur = true
dimensions = { columns = 200, lines = 60 }
decorations_theme_variant = "Dark"

[font]
normal.family = "Hack Nerd Font Mono"
normal.style = "Regular"
bold.family = "Hack Nerd Font Mono"
bold.style = "Bold"
italic.family = "Hack Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "Hack Nerd Font Mono"
bold_italic.style = "Bold Italic"

[env]
TERM = "xterm-256color"

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
